puts "Adding words to the game!"

Word.create(scrambled: "IELRNG", answer: "LINGER", hint1: "stay...", hint2: "lag...", hint2: "loiter...", hint3: "stay put...", initial_hint: "dawdle...")
Word.create(scrambled: "TSROYRFE",answer: "FORESTRY", hint1: "woodcraft...", hint2: "Arboriculture...", hint3: "trees...", initial_hint: "nature...")
Word.create(scrambled: "DCIIRTNMIINSAO",answer: "DISCRIMINATION", hint1: "hatred...", hint2: "differential...", hint3: "bigotry...", initial_hint: "partisan...")
Word.create(scrambled: "ILMRPACIE",answer: "EMPIRICAL", hint1: "pragmatic...", hint2: "speculative...", hint3: "tried and true...", initial_hint: "I'd like to think scientists probably say this word a bunch")
Word.create(scrambled: "TSNAIDAIMRNITO",answer: "ADMINISTRATION", hint1: "they manage or make decisions", hint2: "think leadership", hint3: "Think government, I don't know what else to tell you.", initial_hint: "authority...")
Word.create(scrambled: "SPAEEl",answer: "ELAPSE", hint1: "slide by", hint2: "go by", hint3: "pass by", initial_hint: "move past")
Word.create(scrambled: "ONSERSPPKESO",answer: "SPOKESPERSON", hint1: "voice", hint2: "herald", hint3: "mouthpiece...", initial_hint: "Flo from progressive, the Keebler Elf, Siri?")
Word.create(scrambled: "OVIAEORTPEC",answer: "COOPERATIVE", hint1: "communal", hint2: "amenable", hint3: "teamwork", initial_hint: "synergetic ...")
Word.create(scrambled: "EARSMDMITN",answer: "MASTERMIND", hint1: "think architect...", hint2: "think formulator", hint3: "think ringleader", initial_hint: "Lex Luthor, Dr. Robotnik, Norman Osborn, Michael Scofield")
Word.create(scrambled: "RTETDRAIEEO",answer: "DETERIORATE", hint1: "go bad...", hint2: "to wear", hint3: "abate maybe?", initial_hint: "its getting worse")
Word.create(scrambled: "YOIOPSLPHH",answer: "PHILOSOPHY", hint1: "all the isms, well a lot of them atleast", hint2: "credo...", hint3: "doctrine...", initial_hint: "Theres a bunch of these but you could say some are like nonviolence, cosmism, nihilism, ooh or a fancy one like neorealism")
Word.create(scrambled: "VAERGNSIDIT",answer: "ADVERTISING", hint1: "think publicists", hint2: "slogans...", hint3: "fliers...", initial_hint: "These are literally EVERYWHERE...i know that helped a bunch right 😉")
Word.create(scrambled: "TAECVAXE",answer: "EXCAVATE", hint1: "unearth...", hint2: "spade...", hint3: "burrow...", initial_hint: "scoop")
Word.create(scrambled: "FAYNIIFT",answer: "AFFINITY", hint1: "relation...", hint2: "kinship...", hint3: "rapport...", initial_hint: "a fancy word that can describe how you feel about someone you like.")
Word.create(scrambled: "VIDEDNID",answer: "DIVIDEND", hint1: "bonus...", hint2: "think finance and economics...", hint3: "think operand...", initial_hint: "cumulative stock")
Word.create(scrambled: "AFBEOHLNIAS",answer: "FASHIONABLE", hint1: "voguish...", hint2: "hip...", hint3: "trendy...", initial_hint: "posh...")
Word.create(scrambled: "ERAPAP",answer: "APPEAR", hint1: "arise...", hint2: "show...", hint3: "emerge...", initial_hint: "show...")
Word.create(scrambled: "ORLVE",answer: "LOVER", hint1: "suitor...", hint2: "swain...", hint3: "soulmate...", initial_hint: "dear...")
Word.create(scrambled: "ECCTRHTRUAEI",answer: "ARCHITECTURE", hint1: "structure...", hint2: "construction...", hint3: "formation...", initial_hint: "design...")
Word.create(scrambled: "NNMITOEA",answer: "NOMINATE", hint1: "anoint...", hint2: "propose...", hint3: "approve...", initial_hint: "appoint...")
Word.create(scrambled: "NECHCA",answer: "CHANCE", hint1: "possibility...", hint2: "probability...", hint3: "luck of the draw...", initial_hint: "opportunity...")
Word.create(scrambled: "SIUES",answer: "ISSUE", hint1: "topic...", hint2: "matter at hand...", hint3: "discharge...", initial_hint: "edition...")
Word.create(scrambled: "HSAD",answer: "DASH", hint1: "hurtle...", hint2: "hustle...", hint3: "sprint...", initial_hint: "bustle...")
Word.create(scrambled: "OANEOPTARIL",answer: "OPERATIONAL", hint1: "up and running...", hint2: "servicable...", hint3: "in action...", initial_hint: "functional...")
Word.create(scrambled: "ATEEGRTDNI",answer: "INTEGRATED", hint1: "unified...", hint2: "link...", hint3: "combined...", initial_hint: "binding...")
Word.create(scrambled: "ORNWE",answer: "OWNER", hint1: "holder...", hint2: "inheritor...", hint3: "possessor...", initial_hint: "caretaker...")
Word.create(scrambled: "OTDEISP",answer: "DEPOSIT", hint1: "to place...", hint2: "lay...", hint3: "put...", initial_hint: "lodge...")
Word.create(scrambled: "SBRNALOEEA",answer: "REASONABLE", hint1: "", hint2: "logical...", hint3: "amenable...", initial_hint: "rational...")
Word.create(scrambled: "TNUNNSIG",answer: "STUNNING", hint1: "astonishing...", hint2: "amazing...", hint3: "grand...", initial_hint: "awesome...")
Word.create(scrambled: "SEEPXO",answer: "EXPOSE", hint1: "uncover...", hint2: "unveil...", hint3: "reveal...", initial_hint: "unmask...")
Word.create(scrambled: "ANTIROEC",answer: "CREATION", hint1: "beginning", hint2: "formation...", hint3: "construction...", initial_hint: "invention...")
Word.create(scrambled: "EONYM",answer: "MONEY", hint1: "moola...", hint2: "funds...", hint3: "cash...", initial_hint: "dough...")
Word.create(scrambled: "AEKSREP",answer: "SPEAKER", hint1: "sayer...", hint2: "herald...", hint3: "utterer...", initial_hint: "orator...")
Word.create(scrambled: "NECOYOM",answer: "ECONOMY", hint1: "resources...", hint2: "financial system...", hint3: "regulation...", initial_hint: "recession...")
Word.create(scrambled: "SAEOTHG",answer: "HOSTAGE", hint1: "captive...", hint2: "bounded...", hint3: "prisoner...", initial_hint: "detained...")
Word.create(scrambled: "HRACE",answer: "REACH", hint1: "acquire...", hint2: "within your grasp...", hint3: "obtain...", initial_hint: "attain...")
Word.create(scrambled: "LCNIIC",answer: "CLINIC", hint1: "infirmary...", hint2: "sick bay...", hint3: "health center...", initial_hint: "hospital...")
Word.create(scrambled: "ELNBO",answer: "NOBLE", hint1: "proud...", hint2: "distinguished...", hint3: "grand...", initial_hint: "great...")
Word.create(scrambled: "NYED",answer: "DENY", hint1: "refuse...", hint2: "refute...", hint3: "negate...", initial_hint: "disavow...")
Word.create(scrambled: "OGDNRA",answer: "DRAGON", hint1: "fantasy creature...", hint2: "scales...", hint3: "fire breathing...", initial_hint: "monster...")
Word.create(scrambled: "ITEODIN",answer: "EDITION", hint1: "publication...", hint2: "version...", hint3: "issue...", initial_hint: "print...")
Word.create(scrambled: "MALP",answer: "PALM", hint1: "paw...", hint2: "mitt...", hint3: "hand...", initial_hint: "tree...")
Word.create(scrambled: "ESMT",answer: "STEM", hint1: "branch...", hint2: "shank...", hint3: "stalk...", initial_hint: "sprig...")
Word.create(scrambled: "OUELPC",answer: "COUPLE", hint1: "two...", hint2: "duo...", hint3: "pair...", initial_hint: "item...")
Word.create(scrambled: "EEDNSATRPI",answer: "PEDESTRIAN", hint1: "stroller...", hint2: "passerby...", hint3: "hiker...", initial_hint: "wayfarer...")
Word.create(scrambled: "NEWI",answer: "WINE", hint1: "booze...", hint2: "red...", hint3: "spirits...", initial_hint: "glass...")
Word.create(scrambled: "ADI",answer: "AID", hint1: "help...", hint2: "support...", hint3: "relieve...", initial_hint: "assist...")
Word.create(scrambled: "NAECLNH",answer: "CHANNEL", hint1: "canal...", hint2: "trough...", hint3: "stream...", initial_hint: "strait...")
Word.create(scrambled: "ERTA",answer: "RATE", hint1: "fare...", hint2: "pace...", hint3: "speed...", initial_hint: "tempo...")
Word.create(scrambled: "DEGILOOY",answer: "IDEOLOGY", hint1: "outlook...", hint2: "tenets...", hint3: "credo...", initial_hint: "belief...")
Word.create(scrambled: "PIMRTO",answer: "IMPORT", hint1: "abroad...", hint2: "buy in...", hint3: "bring in...", initial_hint: "take in...")
Word.create(scrambled: "RWRONA",answer: "NARROW", hint1: "limited...", hint2: "thin...", hint3: "slim...", initial_hint: "taper...")
Word.create(scrambled: "TIERMB",answer: "TIMBER", hint1: "wood...", hint2: "tree...", hint3: "cedar...", initial_hint: "lumber...")
Word.create(scrambled: "LYIL",answer: "LILY", hint1: "aloe...", hint2: "flower...", hint3: "lotus...", initial_hint: "petal...")
Word.create(scrambled: "INLAF",answer: "FINAL", hint1: "decisive...", hint2: "ending...", hint3: "last...", initial_hint: "ultimate...")
Word.create(scrambled: "VVTEEL",answer: "VELVET", hint1: "down...", hint2: "soft...", hint3: "lucious...", initial_hint: "fabric")
Word.create(scrambled: "PTIR",answer: "TRIP", hint1: "excursion...", hint2: "tour...", hint3: "journey...", initial_hint: "visit...")
Word.create(scrambled: "ROFK",answer: "FORK", hint1: "trident", hint2: "silverware...", hint3: "utensil...", initial_hint: "diverge...")
Word.create(scrambled: "CNFETI",answer: "INFECT", hint1: "taint...", hint2: "contaminate...", hint3: "poison...", initial_hint: "affect...")
Word.create(scrambled: "IEVACEH",answer: "ACHIEVE", hint1: "accomplish...", hint2: "reach...", hint3: "obtain...", initial_hint: "attain...")
Word.create(scrambled: "EITNTAP",answer: "PATIENT", hint1: "docile...", hint2: "calm...", hint3: "tolerant...", initial_hint: "lax...")
Word.create(scrambled: "ESNSENON",answer: "NONSENSE", hint1: "gibberish...", hint2: "boloney...", hint3: "malarky...", initial_hint: "drivel...")
Word.create(scrambled: "RKCA",answer: "RACK", hint1: "stand...", hint2: "support...", hint3: "shelf...", initial_hint: "holder...")
Word.create(scrambled: "OPTMCCA",answer: "COMPACT", hint1: "close...", hint2: "compress...", hint3: "constrict...", initial_hint: "dense...")
Word.create(scrambled: "UDYST",answer: "STUDY", hint1: "review...", hint2: "research...", hint3: "learning...", initial_hint: "cramming...")
Word.create(scrambled: "OLWG",answer: "GLOW", hint1: "emit...", hint2: "shine....", hint3: "aura...", initial_hint: "radiate...")
Word.create(scrambled: "TSROP",answer: "SPORT", hint1: "recreation...", hint2: "exercise...", hint3: "game...", initial_hint: "play...")
Word.create(scrambled: "LOYDBO",answer: "BLOODY", hint1: "gaping...", hint2: "sanguinary...", hint3: "raw...", initial_hint: "gory...")
Word.create(scrambled: "TLINSOOU",answer: "SOLUTION", hint1: "blend...", hint2: "key...", hint3: "answer...", initial_hint: "remedy...")
Word.create(scrambled: "AEHRETC",answer: "TEACHER", hint1: "lecturer...", hint2: "mentor...", hint3: "educator...", initial_hint: "tutor...")
Word.create(scrambled: "UHGE",answer: "HUGE", hint1: "gigantic...", hint2: "vast...", hint3: "massive...", initial_hint: "immense...")
Word.create(scrambled: "VEOHR",answer: "HOVER", hint1: "elevate...", hint2: "soar...", hint3: "float...", initial_hint: "linger...")
Word.create(scrambled: "HAFICERNS",answer: "FRANCHISE", hint1: "privilege....", hint2: "permission...", hint3: "license...", initial_hint: "charter...")
Word.create(scrambled: "ETANCIB",answer: "CABINET", hint1: "container...", hint2: "closet...", hint3: "cupboard...", initial_hint: "locker...")
Word.create(scrambled: "MOTETNCP",answer: "CONTEMPT", hint1: "scorn...", hint2: "dislike...", hint3: "despite...", initial_hint: "disdain...")
Word.create(scrambled: "CIERACSFI",answer: "SACRIFICE", hint1: "loss...", hint2: "cost...", hint3: "forgo...", initial_hint: "forfeit...")
Word.create(scrambled: "MDOISU",answer: "SODIUM", hint1: "halite...", hint2: "seawater...", hint3: "Na...", initial_hint: "metallic element...")
Word.create(scrambled: "NLDAIS",answer: "ISLAND", hint1: "archipelago...", hint2: "bali...", hint3: "cuba...", initial_hint: "atoll...")
Word.create(scrambled: "EAABNLC",answer: "BALANCE", hint1: "equilibrium...", hint2: "steadiness...", hint3: "stabilize...", initial_hint: "poise...")
Word.create(scrambled: "OTMUTINA",answer: "MUTATION", hint1: "anomaly...", hint2: "alteration...", hint3: "variant...", initial_hint: "transfiguration...")
Word.create(scrambled: "TATNNE",answer: "TENANT", hint1: "resident...", hint2: "occupant...", hint3: "renter...", initial_hint: "lodger...")
Word.create(scrambled: "ONWDR",answer: "DROWN", hint1: "submerge...", hint2: "overwhelm...", hint3: "flood...", initial_hint: "engulf...")
Word.create(scrambled: "OVTLNIIAO",answer: "VIOLATION", hint1: "error...", hint2: "transgression...", hint3: "breach...", initial_hint: "abuse...")
Word.create(scrambled: "HCIDL",answer: "CHILD", hint1: "tyke...", hint2: "son...", hint3: "youngster...", initial_hint: "tot...")
Word.create(scrambled: "EEPTTPIA",answer: "APPETITE", hint1: "longing...", hint2: "hankering...", hint3: "craving...", initial_hint: "hunger...")
Word.create(scrambled: "ITNW",answer: "TWIN", hint1: "double...", hint2: "pair...", hint3: "copy...", initial_hint: "dual...")
Word.create(scrambled: "NRUAETL",answer: "NEUTRAL", hint1: "unaffiliated...", hint2: "impartial...", hint3: "uninfluenced...", initial_hint: "nonaligned...")
Word.create(scrambled: "DISPRE",answer: "SPIDER", hint1: "8 legs...", hint2: "insect...", hint3: "arachnid...", initial_hint: "spinner...")
Word.create(scrambled: "EBDAR",answer: "BREAD", hint1: "bun...", hint2: "food...", hint3: "roll...", initial_hint: "loaf...")
Word.create(scrambled: "HTACIRU",answer: "HAIRCUT", hint1: "cut...", hint2: "perm...", hint3: "style...", initial_hint: "trim...")
Word.create(scrambled: "PCIITILM",answer: "IMPLICIT", hint1: "unspoken...", hint2: "unexpressed...", hint3: "wordless...", initial_hint: "tacit...")
Word.create(scrambled: "ESJT",answer: "JEST", hint1: "gag...", hint2: "silliness...", hint3: "quip...", initial_hint: "joke...")
Word.create(scrambled: "HTSUO",answer: "SHOUT", hint1: "bellow...", hint2: "roar...", hint3: "holler...", initial_hint: "bawl...")
Word.create(scrambled: "LBLE",answer: "BELL", hint1: "toll...", hint2: "alarm...", hint3: "ring...", initial_hint: "chime...")
Word.create(scrambled: "HNCPU",answer: "PUNCH", hint1: "attack...", hint2: "strike...", hint3: "slug...", initial_hint: "sock...")
Word.create(scrambled: "NEEDFD",answer: "DEFEND", hint1: "preserve...", hint2: "safeguard...", hint3: "protect...", initial_hint: "barricade...")
Word.create(scrambled: "LOOCNY",answer: "COLONY", hint1: "fief...", hint2: "dependency...", hint3: "province...", initial_hint: "settlement...")
Word.create(scrambled: "CMAO",answer: "COMA", hint1: "blur...", hint2: "daze...", hint3: "blackout...", initial_hint: "stupor...")
Word.create(scrambled: "RFAYI",answer: "FAIRY", hint1: "sprite...", hint2: "imp...", hint3: "pixy...", initial_hint: "fay...")
Word.create(scrambled: "OKA",answer: "OAK", hint1: "pine...", hint2: "tree...", hint3: "wood...", initial_hint: "timber...")
Word.create(scrambled: "RWA",answer: "WAR", hint1: "campaign...", hint2: "fight...", hint3: "clash...", initial_hint: "battle...")


puts "Words have been added!"