puts "Adding words to the game!"

Word.create(scrambled: "IELRNG", answer: "LINGER", hint1: "Another word for stay", hint2: "Another word for lag", hint2: "Another word for loiter", hint3: "Word meaning stay put", initial_hint: "why are ya just standing there like that?")
Word.create(scrambled: "TSROYRFE",answer: "FORESTRY", hint1: "another word for woodcraft", hint2: "Arboriculture is a synonym", hint3: "hmm.... think trees maybe", initial_hint: "something quite.... naturey")
Word.create(scrambled: "DCIIRTNMIINSAO",answer: "DISCRIMINATION", hint1: "this is done towards groups of people", hint2: "There are better synonyms but lets go with - differential", hint3: "partisan is a related word", initial_hint: "if you take part in this your no bueno 😬")
Word.create(scrambled: "ILMRPACIE",answer: "EMPIRICAL", hint1: "think pragmatic", hint2: "Ok that didn't work... maybe try thinking about similar words to speculative.", hint3: "tried and true...", initial_hint: "I'd like to think scientists probably say this word a bunch")
Word.create(scrambled: "TSNAIDAIMRNITO",answer: "ADMINISTRATION", hint1: "they manage or make decisions", hint2: "think leadership", hint3: "Think government, I don't know what else to tell you.", initial_hint: "usually if your in one of these your probably pretty important")
Word.create(scrambled: "SPAEEl",answer: "ELAPSE", hint1: "slide by", hint2: "go by", hint3: "pass by", initial_hint: "move past")
Word.create(scrambled: "ONSERSPPKESO",answer: "SPOKESPERSON", hint1: "voice", hint2: "herald", hint3: "mouthpiece...", initial_hint: "Flo from progressive, the Keebler Elf, Siri?")
Word.create(scrambled: "OVIAEORTPEC",answer: "COOPERATIVE", hint1: "communal", hint2: "amenable", hint3: "teamwork", initial_hint: "synergetic ...")
Word.create(scrambled: "EARSMDMITN",answer: "MASTERMIND", hint1: "think architect...", hint2: "think formulator", hint3: "think ringleader", initial_hint: "Lex Luthor, Dr. Robotnik, Norman Osborn, Michael Scofield")
Word.create(scrambled: "RTETDRAIEEO",answer: "DETERIORATE", hint1: "go bad...", hint2: "to wear", hint3: "abate maybe?", initial_hint: "its getting worse")
Word.create(scrambled: "YOIOPSLPHH",answer: "PHILOSOPHY", hint1: "all the isms, well a lot of them atleast", hint2: "credo...", hint3: "doctrine...", initial_hint: "Theres a bunch of these but you could say some are like nonviolence, cosmism, nihilism, ooh or a fancy one like neorealism")
Word.create(scrambled: "VAERGNSIDIT",answer: "ADVERTISING", hint1: "think publicists", hint2: "slogans...", hint3: "fliers...", initial_hint: "These are literally EVERYWHERE...i know that helped a bunch right 😉")
Word.create(scrambled: "TAECVAXE",answer: "EXCAVATE", hint1: "unearth...", hint2: "spade...", hint3: "burrow...", initial_hint: "scoop")
Word.create(scrambled: "FAYNIIFT",answer: "AFFINITY", hint1: "relation...", hint2: "kinship...", hint3: "rapport...", initial_hint: "a fancy word that can describe how you feel about someone you like.")
Word.create(scrambled: "VIDEDNID",answer: "DIVIDEND", hint1: "bonus...", hint2: "think finance and economics...", hint3: "think operand...", initial_hint: "cumulative stock")
Word.create(scrambled: "AFBEOHLNIAS",answer: "FASHIONABLE", hint1: "voguish...", hint2: "hip...", hint3: "trendy...", initial_hint: "posh...")
Word.create(scrambled: "ERAPAP",answer: "APPEAR", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ORLVE",answer: "LOVER", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ECCTRHTRUAEI",answer: "ARCHITECTURE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "NNMITOEA",answer: "NOMINATE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "NECHCA",answer: "CHANCE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "SIUES",answer: "ISSUE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "HSAD",answer: "DASH", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "OANEOPTARIL",answer: "OPERATIONAL", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ATEEGRTDNI",answer: "INTEGRATED", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ORNWE",answer: "OWNER", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "OTDEISP",answer: "DEPOSIT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "SBRNALOEEA",answer: "REASONABLE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "TNUNNSIG",answer: "STUNNING", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "SEEPXO",answer: "EXPOSE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ANTIROEC",answer: "CREATION", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "YMENO",answer: "MONEY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "AEKSREP",answer: "SPEAKER", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "NECOYOM",answer: "ECONOMY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "SAEOTHG",answer: "HOSTAGE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "HRACE",answer: "REACH", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "LCNIIC",answer: "CLINIC", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ELNBO",answer: "NOBLE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "NYED",answer: "DENY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "OGDNRA",answer: "DRAGON", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ITEODIN",answer: "EDITION", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "MLAP",answer: "PALM", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ESTM",answer: "STEM", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "OUELPC",answer: "COUPLE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "EEDNSATRPI",answer: "PEDESTRIAN", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "NEWI",answer: "WINE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ADI",answer: "AID", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "NAECLNH",answer: "CHANNEL", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ERTA",answer: "RATE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "DEGILOOY",answer: "IDEOLOGY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "PIMRTO",answer: "IMPORT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "RWRONA",answer: "NARROW", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "TIERMB",answer: "TIMBER", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "LYIL",answer: "LILY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "INLAF",answer: "FINAL", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "VVTEEL",answer: "VELVET", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "PTIR",answer: "TRIP", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ROFK",answer: "FORK", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "CNFETI",answer: "INFECT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "IEVACEH",answer: "ACHIEVE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "EITNTAP",answer: "PATIENT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "ESNSENON",answer: "NONSENSE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "RKCA",answer: "RACK", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "OPTMCCA",answer: "COMPACT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "STUDY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "GLOW", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "SPORT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "BLOODY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "SOLUTION", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "TEACHER", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "HUGE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "HOVER", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "FRANCHISE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "CABINET", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "CONTEMPT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "SACRIFICE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "SODIUM", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "ISLAND", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "BALANCE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "MUTATION", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "CARBON", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "DROWN", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "VIOLATION", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "CHILD", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "APPETITE", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "TWIN", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "NEUTRAL", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "SPIDER", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "BREAD", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "HAIRCUT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "IMPLICIT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "JEST", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "SHOUT", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "BELL", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "PUNCH", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "DEFEND", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "COLONY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "COMA", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "FAIRY", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "OAK", hint1: "", hint2: "", hint3: "", initial_hint: "")
Word.create(scrambled: "",answer: "WAR", hint1: "", hint2: "", hint3: "", initial_hint: "")


puts "Words have been added!"